### ISSUE TITLE
Rank999FirstAccessibleKeyNumber incorrectly always set to 1 

### ISSUE THREAD

**Issue by kwhite-uottawa** [GrandOrgue/OdfEdit#24]
In, for example, the AVO positive sample set  [https://hauptwerk-augustine.info/Stahlhuth_positive.php](url) stops combine ranks at different parts of the keyboard.  OdfEdit.py (v2.4) incorrectly places all converted ranks starting at 1 instead of at 26 or 25.

Attached is the HW file, the file converted to GO by OdfEdit, and a hand tweaked version.  This tweaked version fixes the AccessibleKeyNumber,  cleans up some graphical elements, and adds the key action noises.

[I see in OdfEdit.py that action noises are TBD.  In this case I generated them using sqlite (action.sh included in the zipfile) on the imported HW xml.  I don't know if that is of any use!]

[stahlhuth.zip](https://github.com/GrandOrgue/ODFEdit/files/11688407/stahlhuth.zip)

**Comment by eturpault** [comment]
This is an interrestiong sample set with some unusual characteristics, thank you for this feedback. 
- the text of some labels has carriage return characters inside the string, which is not supported in GO, OdfEdit has to replace them by blank spaces.
- the drawstop are defined by two dissociated objects : a switch which defines the image of the drawstop and a label without background which defines the text to display inside the image. There is no possibility to associate them together and to create a GO switch with both text and image attributes (as you did manually in your fixed ODF). The text is not visible in the panel because it is displayed behind the image by GO. GO should display the labels in a layer over the one of the images. I will submit a change request for that.
- the attribute MIDINoteNumIncrementFromDivisionToRank is not defined in the StopRank objects of the ranks which are starting from MIDI 61 (it is defined in the other sample sets that I tested so far), it is the reason why Rank999FirstAccessibleKeyNumber is set at 1 for these stops, I have to find a way to manage this missing increment attribute, using the MIDI values of the pipes.

Thanks for the example of key action noises implementation, it may help me when I will implement it in OdfEdit.

**Comment by kwhite-uottawa** [comment]
If it helps, I used the following on the sqlite import of the HW XML to find the offsets.  Looks a bit dense in github "insert code" format, but really just simple joins...

`select
        StopID
        , RankID
        , Division.Name DivisionName
        , Stop.Name StopName
        , Rank.Name RankName
        , printf('%03d', dense_rank() over (partition by StopID order by RankID+0)) rankno
        , min(coalesce(NormalMIDINoteNumber,'60')+0) FirstMIDINoteNumber
        , min(coalesce(NormalMIDINoteNumber,'60')+0) - (InpGen_MIDINoteNumberOfFirstInput-1) FirstAccessibleKeyNumber
from Pipe_SoundEngine01
join Rank
        using(RankID)
join StopRank
        using (RankID)
join Stop
        using(StopID)
join Division
        using(DivisionID)
where
        ActionEffectCode='1'
group by
        StopID, RankID, StopName, RankName, DivisionName
;
`

|StopID|RankID|DivisionName|StopName|RankName|rankno|FirstMIDINoteNumber|FirstAccessibleKeyNumber|
|----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- |
|2101|1|GREAT|2101_Holzgedeckt 8'|GRT- 1 Holzgedeckt 8'|001|36|1|
|2101|2|GREAT|2101_Holzgedeckt 8'|GRT- 2 Holzgedeckt_d 8'|002|61|26|
|2105|5|GREAT|2105_Rohrfloete 4'|GRT- 5 Rohrfloete 4'|001|36|1|
|2105|6|GREAT|2105_Rohrfloete 4'|GRT- 6 Rohrfloete_d 4'|002|61|26|
|2107|7|GREAT|2107_Flachfloete 2'|GRT- 7 Flachfloete 2'|001|36|1|
|2107|8|GREAT|2107_Flachfloete 2'|GRT- 8 Flachfloete_d 2'|002|61|26|
|2109|9|GREAT|2109_Spitzquinte 1 1/3'|GRT- 9 Spitzquinte 1 1/3'|001|36|1|
|2109|10|GREAT|2109_Spitzquinte 1 1/3'|GRT- 10 Spitzquinte_d 1 1/3'|002|61|26|
|2111|11|GREAT|2111_Spitzquinte_D1|GRT- 11 Spitzquinte_D2|001|60|25|
|2112|12|GREAT|2112_Spitzquinte_D2|GRT- 12 Spitzquinte_D3|001|61|26|
|2690|91|NOISES|Stop: Noises: Blower|Noises: Blower|001|60|25|

**Comment by eturpault** [comment]
Thanks, it has permitted me to double check my fix. But I will still set Rank999FirstAccessibleKeyNumber=1 for this sample set  because I set FirstAccessiblePipeLogicalKeyNumber=26.
This is because Rank999FirstAccessibleKeyNumber is the "Key number **offset** (starting with FirstAccessiblePipeLogicalKeyNumber) for the pipe referenced by Rank999FirstPipeNumber." as said in the help of GO.

**Comment by eturpault** [comment]
This is fixed in OdfEdit v2.5
