### ISSUE TITLE
OdfEdit doesn't recognise multiple HW installation packages

### ISSUE THREAD

**Issue by alebgz-91** [GrandOrgue/OdfEdit#32]
This issue has been found when trying to use OdfEdit with the Buckeburg Vol 1 free sample set from Sonus Paradisi. They allow the user to download the organ sample set in six separate installation packages (.r00 to .f06) none of which is recognised by OdfEdit. 
Sonus Paradisi also offers a .rar file but this only contains an .xml file as organ definition file and again does not get recognised by OdfEdit.

**Comment by larspalo** [comment]
@alebgz-91 You must _first_ download _all_ of the packages. _Then_ you extract the .rar file, which will create a complete de-compressed version of the sample set from _all_ of the archive files. When all that is done you can finally open the definition file for conversion, not before that.

**Comment by eturpault** [comment]
Thanks @larspalo, this is indeed the issue here. The sample set has to be fully decompressed on the computer before OdfEdit can work with it and convert the Hauptwerk ODF (.Organ_Hauptwerk_xml) into a GrandOrgue ODF (.organ) in the folder OrganDefinitions

One must not confuse two types of installation packages : 
- the archive files .rxx provided by the sample set editor to download the sample set, which have to be decompressed on the computer,
- the Hauptwerk installations packages which are the sub-folders (named with 6 digits) and which are located in the folder OrganInstallationPackages, once the downloaded sample set archive has been properly decompressed on the computer.

**Comment by alebgz-91** [comment]
Thanks @larspalo and @eturpault, this is exactly what I did. I downloaded all the packages and extracted the rar file in the computer. A folder called OrganInstallationPackages was then created, this contained a subfolder named with a six digits number. But then the file named ..._Hauptwerk_xml inside this folder isn't recognised by OdfEdit.

**Comment by eturpault** [comment]
What do you mean by "the file is not recognized by OdfEdit" ? What are you trying to do ?
If you are testing Buckeburg, the Hauptwerk ODF is named "Buckeburg, Janke Organ, Surround Demo.Organ_Hauptwerk_xml". In OdfEdit click on the button "Open", in the opened dialog box select the folder ..\BuckeburgVol1\OrganDefinitions, it should show you the files having the extension .organ or .Organ_Hauptwerk_xml, isn't it the case ? 
Then select the file and click on the button Open, OdfEdit will start the loading and conversion of the HW definition file.

**Comment by alebgz-91** [comment]
@larspalo I am indeed trying to test Buckeburg. At this stage I believe there must be something amiss with the files I have downloaded because 1) there is no folder called OrganDefinitions and 2) the only file is in the OrganInstallationPackages folder and it's not called in the way you menton. 
That's very odd, I verified the checksums and they were all ok. I presum you have tried converting this and it worked?

**Comment by eturpault** [comment]
Yes several people, me included, tested without issue the Buckeburg sample set.
Here is the structure of the folders of this sample set that you should get after having decompressed the downloaded archive : 
![image](https://github.com/GrandOrgue/OdfEdit/assets/51839171/0461b076-de06-41cf-a879-79b0c826a41c)
Inside the folder OrganDefinitions you must have the file Buckeburg, Janke Organ, Surround Demo.Organ_Hauptwerk_xml
Maybe you have to download again the sample set archive files from the Sonus Paradisi website and decompress then again on your computer.

**Comment by larspalo** [comment]
> Maybe you have to download again the sample set archive files from the Sonus Paradisi website

Yes, sometimes there can be errors in the download process which can corrupt the archive. That's why it's useful to compare the checksums of the files (md5sum in the case of sonus paradisi) to ensure the integrity, but it's very strange if they actually matched in your tests but still the archive wasn't decompressed correctly. On a related side note, this is also why it's recommended to use a download manager that can resume the download if the connection breaks up at some point.

Anyway, I can confirm that OdfEdit indeed can handle the Buckeburg because I have tested it sucessfully.
