### ISSUE TITLE
Chemnitz-Lutherkirche: PipeGain / St. Jean-de-Luz: HarmonicNumber

### ISSUE THREAD

**Issue by wsc44** [GrandOrgue/OdfEdit#37]
In case of Chemnitz-Lutherkirche (SP) ODFEdit has made great progress from V2.3 to V2.8 . But it seems as if some of its former functionality has been partly lost in between these versions. A comparison of Chemnitz-Sauer-Surround-ODF V2.3 with V2.8 shows that in V2.8 PipeGain is generated only for noise related stuff (tracker, stops etc.), PipeGain-entries for the pipe samples in the ranks are lost. Out of curiosity I checked with Bueckeburg (SP) too. Good news, it seems to be a Chemnitz-specific problem.
A comparison of St. Jean-de-Luz (PG) V2.4 with V2.8 shows that the PipeHarmonicNumber entries seem to have vanished randomly (e.g. Rank004/Flute Harmonique Pipe0012: similar HarmonicNumber-entries in both versions; Pipe0013: HarmonicNumber-entry in V2.8 missing). I can't judge for myself if that's O.K. Maybe it's worth a look. Thanks in advance!

**Comment by eturpault** [comment]
You are right I introduced a regression in OdfEdit v2.7, by ignoring the pipe gains lower than 0 instead of ignoring them when they are equal to 0 (which is the default value of this attribute, no need to set it). It will be fixed in OdfEdit v2.9.
Concerning PipeHarmonicNumber, in OdfEdit v2.8 it is no more converted in the GO ODF if it is equal to 8, which is the default value of this attribute, so not needed in the section.
Thank you for your report.

**Comment by eturpault** [comment]
Fixed in OdfEdit v2.9
