### ISSUE TITLE
Cannot convert HW organ with v2.12

### ISSUE THREAD

**Issue by kerkovits** [GrandOrgue/OdfEdit#57]
When converting HW to GO, Switch999 objects do not have mandatory attribute DefaultToEngaged.

**Comment by eturpault** [comment]
In OdfEdit v2.12 I have made a modification in link with the issue https://github.com/GrandOrgue/grandorgue/issues/1874, in order to define the attribute DefaultToEngaged only when a Drawstop has not the attribute Function or has Function=Input.
If it has an input switch, the state of a Drawstop after loading is set by the initial state of its input switch(es), so DefaultToEngaged is useless. I have seen that it is implemented in this way in GrandOrgue. With this way to do there is no error when loading the ODF in GrandOrgue (even if it is described as required in the help which should be changed as I suggested in the issue 1874).

I see that I have not implemented it correctly, DefaultToEngaged=Y is set but DefaultToEngaged=N is not set, and unfortunately I have not seen this big issue during my validation tests before to release the v2.12...
I will fix it in the next version of OdfEdit to come soon, once I have completed the conversion of tremmed samples of the Piotr Graboswki sample sets.
Thanks for the report.

**Comment by kerkovits** [comment]
Am I right that the problem is line 7665?

**Comment by eturpault** [comment]
Yes you are perfectly right. If you add the following two lines in line 7667 it will solve the issue :
```
            else:
                GO_switch_dic['DefaultToEngaged'] = 'N'
```
In line 7618 the following lines have to be added as well :
```
                    else:
                        GO_object_dic['DefaultToEngaged'] = 'N'
```

**Comment by kerkovits** [comment]
Thank you. I have another issue right now.
