### ISSUE TITLE
Del unexpectely asks for deleting an oblect.

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/OdfEdit#60]
When I am editing in text field (for example, a section content or a search/replace pattern) I expected that Del would delete one character or a text selection. But OdfEdit 2.13 asks me for deletion the whole object chat is edited currently.

Could you take into account the current focus and consider Del as delection of object only if the object hierarchy field is focused now.

**Comment by eturpault** [comment]
Indeed I forgot to take into account this use case when adding the support of the Del key press. I have just added a filtering of this action based on the focused widget.
Do you need that I provide you a new Linux executable with the fix, or can you wait for the next version (using Back space key instead of Del) ?
Thanks for the report.

**Comment by oleg68** [comment]
It is not urgent, so I may wait.

**Comment by eturpault** [comment]
This issue is fixed in OdfEdit v2.14
